# vim:filetype=python:

Import('env')

env.Append(CPPPATH="libsqlite3/include/")
env.Append(CPPPATH="vsqlite++/include/")

files_sqlite=env.Glob("libsqlite3/src/*.c")
lib_sqlite=env.StaticLibrary("libs/vsqlite++-sqlite3",source=files_sqlite)

files_sqlwrap=env.Glob("vsqlite++/src/sqlite/*.cpp")
lib_sqlwrap=env.StaticLibrary("libs/vsqlite++",source=files_sqlwrap)

Default(lib_sqlite,lib_sqlwrap)
